services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_POOL_SIZE: ${DB_POOL_SIZE}

  frontend:
    profiles:
      - frontend
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
